- name: Docker build and push
  hosts: local
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Build Docker Image
      community.docker.docker_image:
        name: petstore
        path: /var/lib/jenkins/workspace/petstore

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: mudit097
        password:  dckr_pat_lbHGcdM_U18z5cSy8TYuXRC4nyc # Use Ansible Vault or environment variables

    - name: Push image
      community.docker.docker_image:
        name: mudit097/petstore
        push: yes

    - name: Run container
      community.docker.docker_container:
        name: pet1
        image: mudit097/petstore:latest
        ports:
          - "8081:8080"
        state: started
